paths:
    content:    'content/'
    layout:     'layout/'
    output:     'output/'

site_preprocessors:
    - class: 'lanyon.processors.blog.TagCollector'
      property: 'tags'
      path: 'posts/'

content_processors:
    - path: '*'
      processors:
          - extensions: [ 'html' ]
            classes: [
                'lanyon.processors.template.YAMLDataExtractor',
                'lanyon.processors.template.Jinja2Renderer'
            ]
          - extensions: [ 'markdown', 'mdown', 'md' ]
            classes: [
                'lanyon.processors.markup.MarkdownRenderer'
            ]
          - extensions: [ 'css', 'js' ]
            classes: [
                'lanyon.processors.template.Jinja2Renderer',
                'lanyon.processors.compression.YUICompressor'
            ]

site_postprocessors:
    - class: 'lanyon.processors.blog.TagPageGenerator'
      tag_template: '_tag.html'
      output_path: 'tags/{tag}.html'

context:
    foo: bar